#!/usr/bin/env bash
set -e

SCRIPT_DIR="$(cd -P "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ENV_FILE="$SCRIPT_DIR/agent-docker.env"

echo "============================================================"
echo " 🤖 Agent Docker Sandbox — Agent Setup & Configuration"
echo "============================================================"
echo "Choose which AI Coding Agents you want to install in your"
echo "isolated Docker container. (y/n)"
echo ""

# Default initial values
source "$ENV_FILE" 2>/dev/null || true
INSTALL_AGY="${INSTALL_AGY:-true}"
INSTALL_CLAUDE="${INSTALL_CLAUDE:-false}"
INSTALL_CODEX="${INSTALL_CODEX:-false}"
INSTALL_OPENCODE="${INSTALL_OPENCODE:-false}"
INSTALL_HERMES="${INSTALL_HERMES:-false}"

# Prompt helper
ask_agent() {
  local name="$1"
  local var_name="$2"
  local current_val="${!var_name}"
  local default_str="n"
  [ "$current_val" = "true" ] && default_str="Y"

  read -r -p "Install $name? [y/n] (Current: $current_val): " answer
  answer="${answer:-$default_str}"
  case "$answer" in
    [Yy]* ) eval "$var_name=true" ;;
    * )     eval "$var_name=false" ;;
  esac
}

ask_agent "Google Antigravity CLI (agy)" "INSTALL_AGY"
ask_agent "Anthropic Claude Code CLI (claude)" "INSTALL_CLAUDE"
ask_agent "OpenAI Codex CLI (codex)" "INSTALL_CODEX"
ask_agent "OpenCode CLI (opencode)" "INSTALL_OPENCODE"
ask_agent "Hermes Agent (hermes)" "INSTALL_HERMES"

echo ""
echo "💾 Saving configuration to $ENV_FILE..."
cat > "$ENV_FILE" <<EOF
# ==============================================================================
# Agent Docker Sandbox Configuration
# Generated by install.sh on $(date)
# ==============================================================================

# Google Antigravity CLI (agy)
INSTALL_AGY=$INSTALL_AGY

# Anthropic Claude Code CLI (claude)
INSTALL_CLAUDE=$INSTALL_CLAUDE

# OpenAI Codex CLI (codex)
INSTALL_CODEX=$INSTALL_CODEX

# OpenCode CLI (opencode)
INSTALL_OPENCODE=$INSTALL_OPENCODE

# Hermes Agent (hermes)
INSTALL_HERMES=$INSTALL_HERMES
EOF

echo "✅ Configuration saved!"
echo "============================================================"
cat "$ENV_FILE"
echo "============================================================"
echo ""
read -r -p "🔨 Rebuild Docker image now with these settings? [Y/n]: " rebuild_answer
rebuild_answer="${rebuild_answer:-Y}"
case "$rebuild_answer" in
  [Yy]* )
    echo "🚀 Starting build..."
    "$SCRIPT_DIR/run.sh" --build
    ;;
  * )
    echo "💡 You can build anytime by running: agent-docker --build"
    ;;
esac
